version: "3.9"

services:
    web:
      build: redis_app/.
      ports:
        - "6000:6000"
      volumes:
        - .:/code
      environment:
        FLASK_ENV: development
    redis:
      image: "redis:alpine"