version: "3.9"

services:
    web:
      build: redis_app/.
      ports:
        - "6000:6000"
      volumes:
        - /Users/luciann/Desktop/training/docker-py-redis/redis_app:/code
    redis:
      image: "redis:alpine"